"""
core.py — Shared download and ringtone logic.
Imported by audio_pull.py (CLI) and app.py (Gradio web UI).
No UI dependencies, no fixed paths — callers pass their own directories.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Optional

import yt_dlp

# ──────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────

RINGTONE_MAX_SECONDS = 40  # hard iPhone limit for ringtones

# The three segments generated by --ringtone-all / "All 3" mode.
# Pattern: 30s clip → skip 15s gap → repeat.
#   intro → 0:00, mid → 0:45 (30+15), outro → 1:30 (45+30+15)
RINGTONE_ALL_SEGMENTS: list[tuple[str, str]] = [
    ("intro", "00:00:00"),
    ("mid",   "00:00:45"),
    ("outro", "00:01:30"),
]


# ──────────────────────────────────────────────────────────────
# yt-dlp helpers
# ──────────────────────────────────────────────────────────────

def build_ydl_opts(
    output_dir: Path,
    audio_format: str,
    embed_metadata: bool,
    archive_path: Optional[Path] = None,
) -> dict:
    """Return yt-dlp options for audio-only extraction.

    `archive_path` enables duplicate-skip tracking. Pass None to disable
    (e.g. the web UI where each session starts fresh).
    """
    postprocessors: list[dict] = [
        {
            "key": "FFmpegExtractAudio",
            "preferredcodec": audio_format,
            "preferredquality": "0",  # best available quality, not a fixed bitrate
        }
    ]
    if embed_metadata:
        postprocessors.append({"key": "FFmpegMetadata", "add_metadata": True})

    opts: dict = {
        "format": "bestaudio/best",
        "outtmpl": str(output_dir / "%(title)s.%(ext)s"),
        "windowsfilenames": True,   # strips illegal chars on Win/Mac/Linux
        "postprocessors": postprocessors,
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        # web_embedded uses YouTube's iframe-player API (no sign-in required, stable SSL).
        # ios is a fallback for videos that restrict embedded playback.
        "extractor_args": {"youtube": {"player_client": ["web_embedded", "ios"]}},
        "retries": 5,
        "fragment_retries": 5,
        "socket_timeout": 30,
    }
    if archive_path:
        opts["download_archive"] = str(archive_path)
    return opts


def download_one(
    url: str,
    ydl_opts: dict,
) -> tuple[str, bool, str, Optional[Path]]:
    """Download audio for one URL.

    Returns (url, success, title_or_error_message, output_path).
    Thread-safe: each call constructs its own YoutubeDL instance.
    """
    captured: list[Path] = []

    def pp_hook(d: dict) -> None:
        if d.get("status") == "finished":
            fp = d["info_dict"].get("filepath")
            if fp:
                captured.append(Path(fp))

    opts = {**ydl_opts, "postprocessor_hooks": [pp_hook]}

    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = (info or {}).get("title", url)
            # captured[-1] is the path after FFmpegExtractAudio changes the extension
            output = captured[-1] if captured else None
            return url, True, title, output
    except yt_dlp.utils.DownloadError as exc:
        return url, False, str(exc), None


# ──────────────────────────────────────────────────────────────
# Ringtone helpers
# ──────────────────────────────────────────────────────────────

def audio_duration(source: Path) -> float:
    """Return duration of an audio file in seconds via ffprobe.
    Returns infinity on failure so callers treat the file as long enough.
    """
    result = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(source),
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    try:
        return float(result.stdout.strip())
    except ValueError:
        return float("inf")


def timestamp_to_seconds(ts: str) -> float:
    """Convert HH:MM:SS, MM:SS, or bare seconds string to a float."""
    parts = [float(p) for p in ts.split(":")]
    if len(parts) == 3:
        return parts[0] * 3600 + parts[1] * 60 + parts[2]
    if len(parts) == 2:
        return parts[0] * 60 + parts[1]
    return parts[0]


def to_ringtone(
    source: Path,
    output_dir: Path,
    start: str,
    duration: int,
    label: Optional[str] = None,
) -> Path:
    """Trim and convert an audio file to iPhone ringtone format (.m4r).

    The .m4r format is AAC audio in an MPEG-4 container — identical to M4A.
    Using `-f ipod` ensures the MP4 atoms are arranged the way iOS expects.
    Pass `label` (e.g. "intro") to append it to the output filename.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{source.stem} [{label}]" if label else source.stem
    out = output_dir / (stem + ".m4r")

    cmd = [
        "ffmpeg", "-y",
        "-i", str(source),
        "-ss", start,
        "-t", str(duration),
        "-c:a", "aac",    # AAC codec (required by iOS)
        "-b:a", "256k",   # 256 kbps; 128 kbps minimum for iOS
        "-f", "ipod",     # MP4 container variant Apple expects for ringtones
        str(out),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8")
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip())
    return out
